- CHANGES.txt
- src/crate/client/sqlalchemy/dialect.py
- src/crate/client/sqlalchemy/dialect.txt
- src/crate/client/sqlalchemy/itests.txt
- src/crate/client/tests.py
- src/crate/testing/tests.py
Add missing dialect attributes from initialize method.
Add tests for the same.
> added missing functionality to cratedialect

- CHANGES.txt
- src/crate/client/sqlalchemy/compiler.py
- src/crate/client/sqlalchemy/tests/create_table_test.py
The create table compiler produces incorrect sql when  'crate_clustered_by' and  'crate_number_of_shards'  ``__table_args__`` are used simultaneously.
In this example I'm using a minimal SQL generated by sqlalchemy:
```sql
cr> CREATE TABLE test (
p STRING
) CLUSTERED INTO 3 SHARDS CLUSTERED BY (p);
CREATE OK (0.077 sec)
cr> select table_name, number_of_shards from information_schema.tables where table_name='test11';
+------------+------------------+
| table_name | number_of_shards |
+------------+------------------+
| test       |                5 |
+------------+------------------+
SELECT 1 row in set (0.002 sec)
```
The number of shards is 5, but it should be 3 ...
The syntax doesn't seem to be valid (according to "[ CLUSTERED [ BY (routing_column) ] INTO num_shards SHARDS ]"), but the …
> Fix sqlalchemy create table compiler

- .travis.yml
- base.cfg
- buildout.cfg
- versions.cfg
somehow the tox recipe doesn't work on travis under
python3.5. I tried to fix that with
https://github.com/gawel/gp.recipe.tox/pull/1 and while that
does fix things for me locally it broke the travis build for
3.3, 3.4 and 3.5 (3.3 is odd because the behaviour for 3.3
is actually unchanged. 3.4 and 3.5 broke because pip is
missing. Which is odd too because `venv.create(..,
with_pip=True)` should ensure that it is there. Which is
actually the case locally, just not on travis).
To work around all that hassle I simply split up the
buildout configurations to not install the tox and sphinx
recipes in the travis run as they're not needed anyway.
> add python3.5 to travis

- base.cfg
- buildout.cfg
- versions.cfg
these dependencies are only useful if one wants to do a release and are
generally not required to run tests
> remove wheel and docutils dependency in base.cfg

- src/crate/testing/layer.txt
44209 is also used in tests.py for the default layer.
> testing: avoid duplicate test layer port

- setup.py
- src/crate/client/http.txt
- src/crate/client/tests.py
- src/crate/testing/layer.py
- src/crate/testing/layer.txt
- tox.ini
- versions.cfg
The functionality that was used of the ServerLayer is
basically just subprocess Popen and kill.
Everything else was either un-used (e.g. stdout/stderr
handling) or unneeded (waiting for the process to become
responsive on its port - the crate layer has that
functionality already with the addition of waiting for HTTP
200 status codes)
> remove lovely.testlayers dependency

- CHANGES.txt
- src/crate/client/http.py
- src/crate/client/test_http.py
Other db-api implementations (e.g. sqlite3) support datetime instances
in `execute` calls.
E.g. it is possible to do something like:
c.execute('insert into t (dt) values (?)', (datetime.utcnow(),))
This commit adds the same functionality.
> add support for datetime serialization

- .travis.yml
- buildout.cfg
- src/crate/client/sqlalchemy/tests/__init__.py
- src/crate/client/sqlalchemy/tests/bulk_test.py
which is new in SQLAlchemy 1.0
see: http://docs.sqlalchemy.org/en/rel_1_0/orm/persistence_techniques.html#bulk-operations
> added test for bulk_save_objects()

- src/crate/client/test_http.py
servers which where set to inactive state
will not be put back to active state immediately, which would cause an endless loop
> increased retry_interval in  ThreadSafeHttpClientTest to ensure that

- CHANGES.txt
- src/crate/client/http.py
- src/crate/client/test_http.py
- src/crate/client/tests.py
Read retries by default are set to 3, which will send an SQL statement up to 4 times if e.g. an read timeout occurs. This commit disables read retries at all.
> disable http retries on read errors

- src/crate/client/http.py
- src/crate/client/test_http.py
- src/crate/client/tests.py
Also adds RequestsCaBundleTest to the testsuite. Before it wasn't
executed
> Move cert removal for non-https into a separate method

- .travis.yml
- CHANGES.txt
- README.rst
- setup.py
- tox.ini
Python 2.6 reached end of line in 2013 and since then doesn't receive
any security updates.
> Drop support for Python 2.6

- CHANGES.txt
- src/crate/testing/layer.py
- src/crate/testing/layer.txt
- src/crate/testing/test_layer.py
- src/crate/testing/tests.py
> do not rely on startup log if static http port for test layer is defined

- CHANGES.txt
- src/crate/testing/layer.py
- src/crate/testing/layer.txt
Set `verbosity=True` will enable the standard output of the Crate
subprocess.
> expose verbosity on test layer

- CHANGES.txt
- src/crate/client/http.py
This pull request addresses the following exception which can occur while fetching blob data from a cluster with multiple non-https servers:
```
Traceback (most recent call last):
File "BlobAccess.py", line 29, in <module>
iter = blob_container.get(blob_dict[k])
File "C:\Anaconda2\envs\sandbox\lib\site-packages\crate\client\blob.py", line 80, in get
return self.conn.client.blob_get(self.container_name, digest)
File "C:\Anaconda2\envs\sandbox\lib\site-packages\crate\client\http.py", line 347, in blob_get
response = self._request('GET', _blob_path(table, digest), stream=True)
File "C:\Anaconda2\envs\sandbox\lib\site-packages\crate\client\http.py", line 406, in _request
raise ProgrammingError(_ex_to_message(e))
crate.client.exceptions.ProgrammingError: __init__() got an unexpected keyword …
```
> Remove certificate keywords when adding non-https server

- CHANGES.txt
- src/crate/client/sqlalchemy/dialect.py
- src/crate/client/sqlalchemy/dialect.txt
- src/crate/client/sqlalchemy/reflection.txt
- src/crate/client/tests.py
* Fix: removed usage of connection.lowest_server_version in get_table_names, cause the passed connection is an SQLAlchemy.BaseConnection which doesn’t  have this attribute
* created an integration test which uses sa.inspect and moved test cases from the dialect integration test
> Fix: get_table_names

- CHANGES.txt
- src/crate/client/sqlalchemy/compiler.py
- src/crate/client/sqlalchemy/tests/__init__.py
- src/crate/client/sqlalchemy/tests/array_test.py
> sqlalchemy: support ARRAY type which was introduced

- CHANGES.txt
- src/crate/client/sqlalchemy/sa_version.py
as StrictVersion(1.1) > StrictVersion(1.1a0) the version checks against alpha and beta versions are wrong
> sqlalchemy: fixed version check agains alpha and beta

- CHANGES.txt
- src/crate/testing/layer.py
- src/crate/testing/layer.txt
- versions.cfg
which is deprecated and will be removed in newer crate versions.
> Fix cmd line settings to be passed with -C and not -Des.

- CHANGES.txt
- src/crate/client/exceptions.py
- src/crate/client/http.py
- src/crate/client/http.txt
- src/crate/client/tests.py
This exception will be raised not only if the table is not a blob table
but also if the table does not exists at all.
The old exception name was wrong for the later situation.
> renames `BlobsDisabledException` to `BlobLocationNotFoundException`

- CHANGES.txt
- src/crate/testing/layer.py
The stdout pipe buffer is limited (and the size varies across systems). We try to read the crate http url from the startup logs (which is rather weird, shouldn't we be using the default port?) and that is our only consumer for the stdout. 
We encountered a problem with this when we tried to switch crate logging to debug. As considerably more log statements (than the default WARNING level we currently use in tests) are issued the pipe buffer overflows. 
As a solution to this, we spawn a thread that consumes the pipe buffer.
> Spawn a thread to consume the stdout

- CHANGES.txt
- src/crate/client/__init__.py
Release changes: 
- Testing: Prevent the process.stdout buffer from filling up in the test layer
which in turn would cause the process to block
- Raise more meaningful `BlobLocationNotFoundException` error when
trying to upload a file to an invalid blob table.
> Prepare release 0.19.1

- CHANGES.txt
- src/crate/client/__init__.py
Release changes:
- Output logs in test-layer in case when CrateDB instance does not start in
time.
- Increased the default timeout for the test-layer startup to avoid timeouts 
on slow hosts.
> Prepare release 0.19.2

- setup.py
This will allow us to drop support for python 2.7 in future version. People
using python 2.7 and a recent version of `pip` will then simply get the old
version. (Instead of the newest, which would likely fail)
> Add python_requires entry to setup.py

- src/crate/client/http.py
- src/crate/client/test_http.py
The new Crate version uses ES 5.4.3 which logs these warnings for every REST request:
```
[WARN ][o.e.d.r.RestController   ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.
[WARN ][o.e.d.r.RestRequest      ] Expected a boolean [true/false] for request parameter [error_trace] but got [1]
```
> Fix deprecation warnings

- src/crate/client/http.py
We have been throwing some errors here but finding out the root cause is hard
without the actual response.
> Add actual response in case of a falsely encoded response

- src/crate/client/http.py
- src/crate/client/test_http.py
Followup of b260d36aa7a03e89a737450d8560fc39af260c2c.
> Send username also with 'X-User' to keep backwards compatibility.

- DEVELOP.rst
I wanted to clarify the release process because I released out of master the last time and wasn't aware that there were feature branches. 
Further, I wanted to explicitly state that the release commit also goes to master. IMHO it should only be in the feature branch but it should be fine since we release out of master most of the time.
> clarify release process in DEVELOP

- src/crate/client/__init__.py
The warning was:
```
.../crate-python/env/lib/python3.6/site-packages/setuptools/dist.py:333: UserWarning: Normalizing '0.22-dev' to '0.22.dev0'
```
> changed dev version to get rid of warning when installing from checkout

- src/crate/client/http.py
- src/crate/client/test_http.py
this fixes the failing RequestsCaBundleTest when run on systems that
have a different path to the CA bundle file than /etc/ssl/certs/ca-certificates.crt
> testing: search for exising CA bundle file

- CHANGES.txt
- src/crate/testing/layer.py
In ES 6 you can either specify a unit (e.g. bytes) or a percentage of the disk
size. If you mix the two, you'll get an error.
> Set watermark.flood_stage to avoid config parsing failure

- CHANGES.txt
- docs/conf.py
* in the newest crate-docs-theme release we added a dependency on `sphinx_sitemap`
* added base url and the extension to build the sitemap in the crate python docs
> added configuration for docs sitemap

- CHANGES.txt
- docs/client.txt
- src/crate/client/connection.py
- src/crate/client/http.py
- src/crate/client/test_http.py
- src/crate/client/tests.py
The client now allows to define a different default schema when connecting to
CrateDB with the ``schema`` keyword argument. This causes all statements and
queries that do not specify a schema explicitly to use the provided schema.
> added schema keyword argument to connect() method

- CHANGES.txt
- docs/blobs.txt
- src/crate/client/blob.py
The blob size is configurable in the http client, but user has no actual access to this. This PR lets the user specify (in bytes) the size of the chunks returned by ``get``ing a blob each iteration. The default is the same as the default in the http client, 128 kilobytes.
> Added ability to specify chunk size when getting a blob from the blob container

- setup.py
We use RST features in these docs that PyPI does not accept.
> Removed client/blob docs from long_description of python package

- src/crate/testing/layer.py
Refs https://docs.python.org/3/library/time.html#time.monotonic
> Use time.monotonic() for elapsed time computation

- tox.ini
tox v2.0 introduced environment variable isolation and thus
the required `JAVA_HOME` variable must be configured to be passed
explicitly.
See https://tox.readthedocs.io/en/latest/changelog.html#v2-0-0-2015-05-12
> Fix tox setup, pass required JAVA_HOME env.

- CHANGES.txt
- src/crate/testing/doctests/layer.txt
- src/crate/testing/layer.py
- src/crate/testing/test_layer.py
This commit changes the default value for `JAVA_HOME` in the
`CrateLayer` from `None` to `''` (empty string). This is necessary,
because environment variables are always interpreted as strings, and
therefore `None` would be interpreted as a string `'None'`, which is not
a valid path for `JAVA_HOME`.
> Default JAVA_HOME env in test layer to empty string

- CHANGES.txt
- src/crate/client/sqlalchemy/dialect.py
- src/crate/client/sqlalchemy/tests/__init__.py
- src/crate/client/sqlalchemy/tests/function_test.py
The `date_trunc` function in CrateDB returns a truncated timestamp based on what period you wish to truncate it to (minute, day, week, etc). This function only works on timestamp columns and returns a timestamp as its result.
However, when calling this function in SQLAlchemy, the returned type is not a `TIMESTAMP` but actually a `NullValue`, as SQLAlchemy is unaware of what the function should return. This autocasts the result set to a number, rather than a python `datetime`.
```
Base = declarative.declarative_base(bind=engine)
class Example(Base):
__tablename__ = 't1'
a = sa.Column("a", sa.DateTime, primary_key=True)
events = session.query(sa.func.date_trunc("minute", Example.a))
for r in events.all():
print(type(r[0]))
>>> <class 'int'>
```
This change, therefore, registers the …
> Register date_trunc function for crate dialect with correct return type

- src/crate/client/sqlalchemy/dialect.py
Using SQL-Alchemy needs the attribute driver.
I simply added `crate-python` as the driver name.
This solves https://github.com/crate/crate-python/issues/348
Added Driver Attribute, which is needed for sqlalchemy
> inserted driver for solving issue #348

- CHANGES.txt
- docs/appendices/data-types.rst
- docs/sqlalchemy.rst
- setup.py
- src/crate/client/doctests/sqlalchemy.txt
- src/crate/client/sqlalchemy/doctests/reflection.txt
- src/crate/client/sqlalchemy/types.py
- src/crate/client/tests.py
- versions.cfg
> Add support for missing geospatial datatypes to SQLAlchemy dialect

- CHANGES.txt
- docs/sqlalchemy.rst
- src/crate/client/sqlalchemy/compiler.py
- src/crate/client/sqlalchemy/dialect.py
Example:
```python
import random
from sqlalchemy import create_engine, inspect, func, Column, String, DateTime
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from sqlalchemy.schema import FetchedValue
engine = create_engine(
"crate://",
connect_args={
"username": "crate",
},
)
Session = sessionmaker(bind=engine)
Base = declarative_base(bind=engine)
class Log(Base):
__tablename__ = "logs"
__table_args__ = {"schema": "doc"}
__mapper_args__ = {"exclude_properties": ["id"]}
id = Column("_id", String, server_default=FetchedValue(), primary_key=True)
ts = Column(DateTime, server_default=func.current_timestamp())
level = Column(String)
message = Column(String)
if __name__ == "__main__":
o = Log(level="info", message="Hello World")
session = …
```
> Add support for RETURNING in SQLAlchemy dialect

- CHANGES.txt
- src/crate/client/connection.py
- src/crate/client/http.py
Hi there,
we have been observing several warnings like these on our live environments:
```
WARNING  [urllib3.connectionpool          ] Connection pool is full, discarding connection: testdrive.cratedb.example.net
```
In order to reproduce these conveniently, you might want to use [`crate-parallel.py`](https://gist.github.com/amotl/575aae129beb17b120b848e7632365dc). It will invoke `SELECT 1;` 100 times in parallel on 10 worker threads and will immediately trigger these warnings. When invoked with the `--pool` parameter - essentially emulating this PR - everything goes along without warnings.
We found out that the [default pool size of `urllib3` is just "1"](https://github.com/urllib3/urllib3/blob/1.25.10/src/urllib3/connectionpool.py#L178), while with the [`requests` module, it is "10" …
> Make connection pool size configurable

- CHANGES.txt
- docs/connect.rst
- src/crate/client/__init__.py
- src/crate/client/connection.py
- src/crate/client/doctests/blob.txt
- src/crate/client/http.py
- src/crate/client/test_http.py
`urllib3` allows to set socket options for individual connections.
Reference: https://urllib3.readthedocs.io/en/latest/reference/urllib3.connection.html#urllib3.connection.HTTPConnection
This should help mitigating problems with environments where idle connections are closed without resetting. This happens e.g. with Azure load balancers.
Reference: https://joonas.fi/2017/01/23/microsoft-azures-networking-is-fundamentally-broken/
> Enable TCP keep alive on socket level

- .github/workflows/release.yml
- DEVELOP.rst
This replaces the manual release of the Crate python driver to PyPi to one done by Github actions, triggered on tag pushes, similar to our Crash project. The pypi API key has already been added to the secrets for this project.
Addresses #378
> Add github action to release project to pypi on tag

- .github/workflows/main.yml
This just bumps to the most recent releases of the 1.1, 1.2 and 1.3 series of SQLAlchemy.
> Test against more recent SQLAlchemy versions on CI

- src/crate/client/doctests/https.txt
This error occurs in some python version tests but not in others - I believe the actual exception message differs across different library versions, but the outcome is ultimately the same.
> Fix failing https.txt test

- .github/workflows/main.yml
- README.rst
Hi there,
this is just a minor update which refreshes the badges displayed within README.rst. However, its main purpose was to investigate why CI tests would not run on #395.
- Adjust and add some badges to README.rst.
- For covering the most recent SQLAlchemy 1.3 release, bump CI to use SQLAlchemy version 1.3.23.
- Also, enable listening to `workflow_dispatch` events in order to be able to trigger workflows manually from the UI.
Andreas.
> Adjust badges, bump SQLAlchemy test version and add "workflow_dispatch"

- docs/connect.rst
- docs/sqlalchemy.rst
- src/crate/client/connection.py
- src/crate/client/doctests/sqlalchemy.txt
Hi there,
there were some more leftovers, where the switchover to "make SSL certificate verification a default" (`verify_ssl_cert=True`, #385) missed out. This patch accounts for that.
Andreas.
> Some adjustments re. switchover to default certificate verification

- src/crate/client/test_http.py
Hi there,
because @mfussenegger said at https://github.com/crate/crate-python/pull/386#discussion_r514057300:
> I'm not keen on building workarounds for problems that should be solved.
this patch provides a better alternative than #386, as it tries to tackle the underlying root cause of one detail which made the testsuite croak on macOS. Specifically, it resolves #398.
By using multiprocessing's ForkProcess, the testsuite will also start working on macOS again, even on Python 3.8+.
The background on this is that beginning with Python 3.8+, "fork" is not the default on all platforms anymore but has been changed to "spawn" on macOS. This method, however, apparently is not compatible with how multiprocessing is currently used within the test harness.
Andreas.
> Tests: Explicitly set multiprocessing start method to "fork"

- src/crate/client/http.py
- src/crate/client/test_http.py
Hi there,
while working on the test suite, I found a glitch, maybe unnoticed more often than not, where active connections have not been closed before removing them from the list of active servers.
Andreas.
> Close urllib3 pool before swapping the server into the "inactive" list

- setup.py
- src/crate/client/http.py
- src/crate/client/tests.py
- versions.cfg
Hi there,
based on this patch, it becomes easier to selectively run parts of the test suite. This is important to me because the whole test suite is currently only able to be invoked exclusively on Linux.
Andreas.
> Improve test suite

- docs/query.rst
In order to improve https://github.com/crate/crate-tutorials/pull/48, this adds some additional references to the documentation.
> Improve references within documentation

- .github/workflows/tests.yml
- .gitignore
- README.rst
- codecov.yml
Hi,
Codecov can receive and process multiple coverage reports for the same job by merging them. That's why we also replaced Coveralls on both PHP repositories `crate-pdo` and `crate-dbal`.
Andreas.
> Use Codecov instead of Coveralls

- .github/workflows/docs.yml
- docs/.gitignore
- docs/Makefile
- docs/appendices/compatibility.rst
- docs/appendices/data-types.rst
- docs/build.json
- docs/conf.py
- docs/connect.rst
- docs/getting-started.rst
- docs/sqlalchemy.rst
Hi there,
this patch improves the state of the onion on all links within the documentation.
- Add [`crate-docs`](https://github.com/crate/crate-docs) build system.
- Run link checker earch morning.
- Rephrase a few spots in order to satisfy the Vale prose linter.
Andreas.
> Documentation: Add link checker to CI and fix broken links

- .github/workflows/nightly.yml
Hi there,
we wanted to check how the nightly jobs can be improved by having them send out notifications about their outcome. This is just a test cycle for investigating how this will work on GHA before converging it into a final version and rolling it out to other repositories.
Andreas.
> CI: Add push notification to nightly build runs

- .github/workflows/nightly.yml
This reverts commit ce8d5e72b2d9ff7b084251ff42e61fed6bd31540. The reason is that it didn't work, see also https://github.com/crate/crate-python/pull/412#issuecomment-833466115.
I might trial this on behalf of a different repository before bringing it back in a functional way.
> Revert "CI: Add push notification to nightly build runs"

- docs/conf.py
Hi there,
this patch slightly adjusts the intersphinx mapping in order to fix `make check` on the documentation.
Andreas.
> Fix documentation checks by adjusting intersphinx mapping

- .github/workflows/tests.yml
- CHANGES.txt
- docs/appendices/data-types.rst
- docs/connect.rst
- docs/sqlalchemy.rst
- src/crate/client/doctests/blob.txt
- src/crate/client/doctests/client.txt
- src/crate/client/doctests/cursor.txt
- src/crate/client/http.py
- src/crate/client/sqlalchemy/dialect.py
- src/crate/client/sqlalchemy/doctests/itests.txt
- src/crate/client/sqlalchemy/tests/connection_test.py
- src/crate/client/test_http.py
- src/crate/client/tests.py
Hi there,
in order to resolve #399, this patch improves some bits when connecting to CrateDB, specifically in scenarios when preferring to connect using a SQLAlchemy DB URI instead of separate `connect_args`. This is convenient for programs which can be configured using a single DB URI as database connection option, like Apache Superset.
- 064e341a4: Accept credentials within the HTTP URI. Example: `http://foo:bar@cratedb.example.org:4200/`
- 52e715d0: Enable SSL using SQLAlchemy DB URI. Example: `crate://cratedb.example.org/?ssl=true`
Andreas.
P.S.: 30fc28e, 93f33b96 and 160aa1e9 are only maintenance commits without feature significance.
> Support credentials and SSL with SQLAlchemy via HTTP/DB URIs

- src/crate/client/doctests/http.txt
- src/crate/client/doctests/mocking.txt
There is a test case which validates that the HTTP client croaks appropriately when connecting to non-CrateDB servers.
https://github.com/crate/crate-python/blob/f773d76b167a296d7f2dd6c85988ed50da251c07/src/crate/client/doctests/http.txt#L184-L191
Within that test, http://crate.io was used as an arbitrary domain to connect to. However, it looks like Fastly now blocks excessive/suspicious requests to that domain, for example when running the test matrix on CI, which invokes quite a number of requests, where their origin might also qualify as "unusual" for some fraud detection algorithms.
> By default, the Signal Sciences agent returns a “406” response code when a request is blocked (similar to an HTTP 406 NOT ACCEPTABLE response).
>
> -- …
> Fix `406 Client Error: Not Acceptable` errors in test suite because new kind of Fastly filtering/blocking

- docs/requirements.txt
The documentation for CrateDB Python version 0.23 still uses an older theme. It maybe is related to the version pinning of Sphinx, which will probably make `pip` select an older version of `crate-docs-theme`.
-- https://crate.io/docs/python/en/0.23/
> Documentation: Fix dependencies for version 0.23

- src/crate/client/sqlalchemy/doctests/itests.txt
- src/crate/client/tests.py
- Hunting an occasional known fluke when running the test suite on CI after midnight.
- Further set the stage for #437.
- Back out of #440, which went too far.
`datetime.date.today()` returns the current local date. So, its outcome depends on the system time zone. Because we want to use UTC-based date and time objects instead, `datetime.utcnow().date()` is a better choice.
> Tests: Use UTC-based `utcnow().date()` instead of localtime-based `date.today()`

- README.rst
- docs/getting-started.rst
Use that canonical command line for advertising the installation of the CrateDB Python driver.
```console
pip install "crate[sqlalchemy]" --upgrade
```
The idea is to show the user right away how to install the most recent version of the CrateDB Python driver together with its SQLAlchemy dialect extension.
We think it is a small but important change to the _installation_ sections of the documentation, which will avoid a lot of frustration for many newcomers. @rafaelasantana, @hammerhead and @proddata will love it.
The other way round, it will be missed by people more often than not, causing general confusion and poor experience on the first time of use.
It is intended for developer folks in general, so it is perfectly fine to tell them about the canonical `pip` incantation, including all …
> Improve installation documentation: Be pragmatic and tell people DWIM

- .github/workflows/nightly.yml
Hi there,
the nightly job run [1] told us that GHA runners `ubuntu-18.04` and `macos-10.15` are deprecated [2,3]. This patch removes them from the list where to run the _Nightly_ jobs on.
Andreas.
[1] https://github.com/crate/crate-python/actions/runs/3004766690
[2] https://github.com/actions/runner-images/issues/6002
[3] https://github.com/actions/runner-images/issues/5583
> GHA runners `ubuntu-18.04` and `macos-10.15` are deprecated

- .github/workflows/docs.yml
- .github/workflows/tests.yml
See https://docs.github.com/en/actions/using-jobs/using-concurrency. Should reduce the resource usage a bit and may speed up things.
Copy of https://github.com/crate/crate/commit/95863241. Thank you, @mfussenegger!
> GHA: Cancel in-progress jobs if pushing to PR

- .github/workflows/nightly.yml
- .github/workflows/tests.yml
- setup.py
Python 3.11 will be released in about a month, on 2022-10-24.
> CI: Add support for Python 3.11

- .github/workflows/tests.yml
Code coverage report upload to Codecov started failing intermittently. Example: https://github.com/crate/crate-python/actions/runs/3177244114/jobs/5177463683
```
[2022-10-03T20:30:53.977Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/)
Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
Error: Codecov: Failed to properly upload: The process '/Users/runner/work/_actions/codecov/codecov-action/v3/dist/codecov' failed with exit code 255
```
<details>
```
Run codecov/codecov-action@v3
==> macos OS detected …
```
> CI: Disable failing on code coverage report upload, Codecov has issues

- .github/workflows/nightly.yml
- CHANGES.txt
- src/crate/client/sqlalchemy/dialect.py
- src/crate/client/sqlalchemy/tests/dialect_test.py
Hi there,
https://github.com/crate/crate/pull/12652, to be released with CrateDB 5.1, introduced an adjustment which needs compensation on the driver level when reflecting the database schema, like https://github.com/crate/pgjdbc/pull/40. It has also been reported as a regression at https://github.com/crate/crate/issues/13102.
Since CrateDB 3.0.0 already, it would have been correct to use the `information_schema.key_column_usage.table_schema` column instead of `table_catalog` (mostly contains value `doc`, the default schema of CrateDB). Now, with CrateDB >=5.1, `table_catalog` will always return `crate`, thus the need for a fix.
With this adjustment, running the test suite against _CrateDB nightly_ succeeds again [^1], where it failed previously on this matter [^2]. …
> Improve SQLAlchemy's `CrateDialect.get_pk_constraint` for CrateDB>=5.1

- CHANGES.txt
- docs/query.rst
- docs/sqlalchemy.rst
- pyproject.toml
- src/crate/client/connection.py
- src/crate/client/converter.py
- src/crate/client/cursor.py
- src/crate/client/doctests/cursor.txt
- src/crate/client/doctests/http.txt
- src/crate/client/http.py
- src/crate/client/test_cursor.py
- src/crate/client/test_http.py
- src/crate/client/test_util.py
- src/crate/client/tests.py
Hi there,
After converging #395 to #437, it became clear / emerged that we wanted to have the type conversion
- only being optionally enabled with a feature flag /cc @mfussenegger 
- being implemented more elegantly /cc @matriv 
This patch aims to resolve both aspects.
This will allow converting fetched data from CrateDB data types to Python data types in different ways. Its usage is completely optional. When not used, the feature will not incur any overhead.
There is also a `DefaultTypeConverter`, which aims to become a sane default choice when looking at this kind of convenience. It will enable the user to work with native Python data types from the start, for all database types where this makes sense, without needing to establish the required set of default value converters on their …
> Add a generic data type converter to the `Cursor` object

- setup.py
Given that the package did not receive any update since 2019, chances are that the next release may bump to a major version, which might not be compatible.
> Dependencies: Limit `geojson` package to version <3

- docs/query.rst
- src/crate/client/doctests/cursor.txt
- src/crate/client/test_cursor.py
Just a variant of #445 in order to re-evaluate https://github.com/pganssle/zoneinfo/issues/122.
> TIMESTAMP->dt: Use ImportError instead of ModuleNotFoundError

- src/crate/client/sqlalchemy/tests/bulk_test.py
- src/crate/client/sqlalchemy/tests/compiler_test.py
- src/crate/client/sqlalchemy/tests/connection_test.py
- src/crate/client/sqlalchemy/tests/dict_test.py
- src/crate/client/sqlalchemy/tests/update_test.py
- src/crate/client/test_cursor.py
- src/crate/client/test_http.py
From the outcome of running a CodeQL scan on behalf of #467, this patch addresses some of the items currently/previously listed at [^1]. Effectively, it will resolve all of the _Imprecise assert_ check notices issued by CodeQL.
[^1]: https://github.com/crate/crate-python/pull/467/checks?check_run_id=9621584111
> Tests: Use more specific assertXXX methods, as suggested by CodeQL

- src/crate/client/tests.py
Stop using deprecated `ssl.wrap_socket()`, use SSL context factory and `context.wrap_socket()` instead.
This was reported as a check failure by CodeQL code scanning (#467) with id `py/insecure-default-protocol` [^1], which translates to »Default version of SSL/TLS may be insecure«.
Use modern alternative SSL context factory methods instead. While `ssl.create_default_context()` was too restrictive, `ssl._create_unverified_context()` was just right, as advertised:
> The configuration is less restrict than `create_default_context()`'s to increase backward compatibility.
On this SSL context, use a minimum version to restrict to secure TLS protocol variants only.
Andreas.
[^1]: https://github.com/github/codeql/blob/main/python/ql/src/Security/CWE-327/InsecureDefaultProtocol.q …
> Tests: Stop using deprecated `ssl.wrap_socket` (Default version of SSL/TLS may be insecure)

- CHANGES.txt
- src/crate/client/sqlalchemy/compiler.py
- src/crate/client/sqlalchemy/tests/compiler_test.py
Hi.
This patch intends to fix #453.
The standard SQLAlchemy statement compiler may generate `LIMIT -1` clauses, but PostgreSQL and CrateDB do not accept them, and need `LIMIT ALL` instead.
The easy solution is to make `CrateCompiler` re-use the existing `PGCompiler.limit_clause`.
Andreas.
> Fix generating appropriate syntax for OFFSET/LIMIT clauses

- CHANGES.txt
- docs/sqlalchemy.rst
- src/crate/client/sqlalchemy/compiler.py
- src/crate/client/sqlalchemy/tests/create_table_test.py
> Support computed columns in SQLAlchemy ORM

- setup.py
This patch is in the same spirit like #458.
Because urllib3 version 2.0 will be published soon [^1], it will be more safe to limit to urllib3 1.x, and to explicitly unlock it when we are sure the code base is compatible. #480 will exercise the update to the most recent alpha release of urllib3 2.x.
[^1]: See also https://pypi.org/project/urllib3/#history.
> Dependencies: Limit to `urllib3>=1.9,<2`, because urllib3-2.x is coming

- CHANGES.txt
- docs/sqlalchemy.rst
- src/crate/client/sqlalchemy/compiler.py
- src/crate/client/sqlalchemy/tests/create_table_test.py
> Add `nullable` and `crate_index` in ORM column definition

- CHANGES.txt
- docs/query.rst
- setup.py
- src/crate/client/connection.py
- src/crate/client/converter.py
- src/crate/client/cursor.py
- src/crate/client/doctests/cursor.txt
- src/crate/client/test_connection.py
- src/crate/client/test_cursor.py
When requested, make the driver return timezone-aware native Python `datetime` objects for CrateDB's `TIMESTAMP` types. The user can easily supply the desired time zone by different means.
@mfussenegger asked at https://github.com/crate/crate-python/pull/442#pullrequestreview-1088223785:
> I think something common like setting the timezone for datetime objects could be made even easier for users.
I shared some initial thoughts about it at https://github.com/crate/crate-python/pull/442#pullrequestreview-1110538218 ff., and finally settled with this implementation, separately from the baseline implementation for the data type converter.
This patch adds additional convenience based on the data type converter machinery added with #442.
- A `time_zone` _keyword argument_ can be passed to both …
> Return `TIMESTAMP` types as timezone-aware native Python `datetime` objects

- src/crate/client/sqlalchemy/tests/dict_test.py
@amotl, this is an attempt at fixing the deprecation warning in `SqlAlchemyDictTypeTest`. I'm not 100% sure about the `test_update_with_dict_column`, this would need manual verification.
> SQLAlchemy deprecation in `SqlAlchemyDictTypeTest`

- src/crate/client/sqlalchemy/tests/dict_test.py
- src/crate/client/sqlalchemy/tests/insert_from_select_test.py
Dear @hammerhead,
regarding your recent patch GH-486 about the fix to `SqlAlchemyDictTypeTest`, I learned more about the details while working on GH-488. Based on the rationale provided below, I think 30d6ea46 is the right fix at this place, **to retain the "qmark" paramstyle** being sent to the driver. It makes sense to look at this very commit only, in order to not get distracted by the other changes induced by reverting your original commit b20fabad0.
Within GH-490, I made the same mistake on overlooking this detail at the `SqlAlchemyInsertFromSelectTest`, and errorneously followed the updated output from the reported diff, effectively accepting a change to the **"named" paramstyle**. efca25e5f gets it right again, by also binding the insert clause to an engine. …
> SA20: Fix SqlAlchemy tests to use "qmark" paramstyle again

- .github/workflows/tests.yml
- bootstrap.sh
- devtools/setup_ci.sh
- src/crate/client/sqlalchemy/tests/compiler_test.py
A flaw with the SQLAlchemy installer for CI has been discovered when running tests on GH-485. It says »Using SQLAlchemy version: 1.4.45« here [^1], while the test matrix slot says it should actually be SA13.
The order of operations was wrong. So, previously, the process would always install SQLAlchemy 1.4, effectively skipping testing on SQLAlchemy 1.3.
Indeed, another fix was needed to compensate for bringing back SA13: 4532ef79fb started using the `PGCompiler` for rendering`LIMIT` clauses, which apparently received a fix with SA14. So, 36a99cad was needed to make one of our test cases compatible with SA13 again.
[^1]: https://github.com/crate/crate-python/actions/runs/3754133520/jobs/6378077603#step:4:222
> CI: Fix installation of defined SQLAlchemy version, bringing back SA13

- docs/by-example/http.rst
For evaluating an error path of the code base, when connecting to non-CrateDB servers, a connection to httpbin.org was made. Apparently, they brought rate limiting in place, so the job would occasionally fail when running on a larger test matrix.
This attempts to resolve GH-493.
> CI: Fix `502 Server Error: Bad Gateway` errors for error path test case

- .github/workflows/tests.yml
The whole test suite weighs in with a total of one hour(!) across all test matrix slots [^1]. I think we can tame that a bit, by running only the most recent version of Python on the matrix slot for macOS. It will also speed up the total runtime.
- **Before:** Run time: 7-11 minutes, Sum: 60 minutes [^1]
- **After:** Run time: 6 minutes, Sum: 33 minutes [^2]
[^1]: https://github.com/crate/crate-python/actions/runs/3758815214/usage
[^2]: https://github.com/crate/crate-python/actions/runs/3759209356/usage
> CI: To save resources, only use the most recent Python version on macOS

- docs/by-example/sqlalchemy/advanced-querying.rst
- docs/by-example/sqlalchemy/crud.rst
- docs/by-example/sqlalchemy/getting-started.rst
- docs/by-example/sqlalchemy/working-with-types.rst
- src/crate/client/sqlalchemy/__init__.py
- src/crate/client/sqlalchemy/compat/api13.py
- src/crate/client/sqlalchemy/tests/__init__.py
- src/crate/client/sqlalchemy/tests/array_test.py
- src/crate/client/sqlalchemy/tests/bulk_test.py
- src/crate/client/sqlalchemy/tests/create_table_test.py
- src/crate/client/sqlalchemy/tests/datetime_test.py
- src/crate/client/sqlalchemy/tests/dialect_test.py
- src/crate/client/sqlalchemy/tests/dict_test.py
- src/crate/client/sqlalchemy/tests/function_test.py
- src/crate/client/sqlalchemy/tests/insert_from_select_test.py
- src/crate/client/sqlalchemy/tests/match_test.py
- src/crate/client/sqlalchemy/tests/update_test.py
Compatibility module for running a subset of SQLAlchemy 2.0 programs on SQLAlchemy 1.3. By using monkey-patching, it can do two things:
1. Add the `exec_driver_sql()` method to SQLAlchemy's `Connection` and `Engine`, forwarding to `execute()`.
2. Amend the `sql.select()` function to accept the calling semantics of the modern variant.
After modernizing the code base, `exec_driver_sql` now is used within the CrateDB dialect, and the new calling semantics of `sql.select` are used within many of the test cases already.
Please note that the patch for `sql.select` is only applied when running the test suite.
- https://github.com/crate/crate-python/pull/485
- https://github.com/crate/crate-python/issues/494
- https://github.com/sqlalchemy/sqlalchemy/issues/8631#issuecomment-1362880407
> SQLAlchemy 2.0: Restore backward-compatibility with SQLAlchemy 1.3

- .github/workflows/codeql.yml
GH-498 displayed multiple admonitions from the CodeQL scan, because the test environment wasn't populated properly with different SQLAlchemy versions. Let's try it again by adding the SQLAlchemy version to the corresponding test matrix.
> CI: Run CodeQL scan on multiple SQLAlchemy versions

- src/crate/client/sqlalchemy/compiler.py
While working on the other refactorings and improvements, I discovered two spots that could be optimized.
> SQLAlchemy: Clean up `CrateCompiler`

- docs/connect.rst
- docs/index.rst
Within the documentation, this patch fixes broken links after renaming folders at https://github.com/crate/crate-sample-apps/pull/95.
> Documentation: Fix broken links

- .github/workflows/codeql.yml
This patch fixes the CodeQL job definition regarding SQLAlchemy package mismatches when running a test matrix on different SQLAlchemy versions.
The CodeQL job definition lacked an appropriate setting for the `category` parameter.
https://github.com/crate/crate-python/blob/696a6239afd28ce6dd52988f65aa511e50629fa8/.github/workflows/codeql.yml#L54-L57
When introducing a matrix axis (here: `sqla-version`), you will have to teach code scanning about it.
https://github.com/crate/crate-python/blob/696a6239afd28ce6dd52988f65aa511e50629fa8/.github/workflows/codeql.yml#L29-L33
Otherwise, it will be obvious that code scanning will get confused by different versions of dependencies.
https://github.com/crate/crate-python/blob/696a6239afd28ce6dd52988f65aa511e50629fa8/.github/workflows/codeql.yml#L49-L52 …
> CI: Fix CodeQL definition

- CHANGES.txt
- src/crate/client/sqlalchemy/__init__.py
- src/crate/client/sqlalchemy/tests/__init__.py
- src/crate/client/sqlalchemy/tests/warnings_test.py
- src/crate/testing/util.py
We decided to drop support for SQLAlchemy 1.3 within one of the upcoming releases and are tracking this at GH-501.
This patch adds a corresponding EOL/deprecation warning to the package, which will be emitted at runtime when running the Python interpreter with default warnings enabled [^enable-warnings][^option-W].
```console
python -Wd -c "import crate.client.sqlalchemy"
PYTHONWARNINGS=default python -c "import crate.client.sqlalchemy"
```
```text
/path/to/crate/client/sqlalchemy/__init__.py:38: DeprecationWarning: WARNING: SQLAlchemy 1.3 is effectively EOL.
With SQLAlchemy 2 around the corner, this will be even more immanent.
Future versions of the CrateDB SQLAlchemy dialect will drop support for SQLAlchemy 1.3.
It is recommended that you transition to using SQLAlchemy 1.4 or 2.0.
``` …
> QA: Add EOL/deprecation warning about support for SQLAlchemy 1.3

- .github/workflows/codeql.yml
- .github/workflows/tests.yml
- CHANGES.txt
- bootstrap.sh
- docs/by-example/sqlalchemy/crud.rst
- setup.cfg
- setup.py
- src/crate/client/sqlalchemy/compat/core10.py
- src/crate/client/sqlalchemy/compat/core14.py
- src/crate/client/sqlalchemy/compat/core20.py
- src/crate/client/sqlalchemy/compiler.py
- src/crate/client/sqlalchemy/dialect.py
- src/crate/client/sqlalchemy/sa_version.py
- src/crate/client/sqlalchemy/tests/bulk_test.py
Based on GH-485 and GH-498, this patch concludes compatibility work with SQLAlchemy 2.0 [^1][^2] (GH-465) 🎉.
[^1]: https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html
[^2]: https://docs.sqlalchemy.org/en/20/changelog/migration_20.html
> Add support for SQLAlchemy 2.0

- DEVELOP.rst
- src/crate/client/sqlalchemy/compat/api13.py
- src/crate/client/sqlalchemy/tests/__init__.py
- src/crate/client/sqlalchemy/tests/connection_test.py
SQLAlchemy's `_ConnectionFairy.connection` attribute will be become deprecated.
> SADeprecationWarning: The _ConnectionFairy.connection attribute is deprecated; please use 'driver_connection' (deprecated since: 2.0)
1. Just use `driver_connection` instead.
2. For SA13, addtionally back-port it.
> SQLAlchemy: Don't use deprecated `_ConnectionFairy.connection` attribute

- src/crate/client/sqlalchemy/dialect.py
The `dbapi()` classmethod on dialect classes has been renamed to `import_dbapi()`.
> SADeprecationWarning: The dbapi() classmethod on dialect classes has been renamed to import_dbapi().  Implement an import_dbapi() classmethod directly on class 'CrateDialect' to remove this warning; the old .dbapi() classmethod may be maintained for backwards compatibility.
Just followed the suggestion 1:1.
> SQLAlchemy: Implement `CrateDialect.import_dbapi` alongside `.dbapi`

- requirements.txt
- setup.py
This PR collects all the individual patches just submitted by Dependabot, accompanied by a little fix 692697e8fd to satisfy the test suite with a specific version of `setuptools<57`. Dependabot will probably submit another patch to bump this specific version again, which can then be addressed separately.
- GH-517
- GH-518
- GH-519
- GH-520
- GH-521
> Maintenance: Address update suggestions by Dependabot

- .coveragerc
- src/crate/client/_pep440.py
- src/crate/client/connection.py
- src/crate/client/sqlalchemy/sa_version.py
- src/crate/testing/test_layer.py
The `distutils` package will become deprecated, see [PEP 632 – Deprecate distutils module](https://peps.python.org/pep-0632/).
> DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
The accepted solution is to vendor [`packaging.version`](https://github.com/pypa/packaging/blob/main/src/packaging/version.py), like how NumPy, pandas and SciPy are doing it equally.
- https://github.com/numpy/numpy/issues/18588
- https://github.com/numpy/numpy/blob/v1.25.0.dev0/numpy/compat/_pep440.py
- https://github.com/pandas-dev/pandas/blob/v1.5.3/pandas/util/version/__init__.py
- https://github.com/scipy/scipy/blob/v1.10.0/scipy/_lib/_pep440.py
> Maintenance (PEP 632): Remove dependency on `distutils`

- setup.py
We learned that, when installing the upcoming `urllib3-2.0.0`, it would effectively drop support for TLS 1.0 and 1.1 by default, and `crate-python` does not offer corresponding fallback adjustments yet. In order not to break things too sloppily, let us postpone this transition, in the spirit of "better safe than sorry".
> If you still need to use TLS 1.0 or 1.1 in your application you can still upgrade to v2.0, you’ll only need to set `ssl_minimum_version` to the proper value to continue using legacy TLS versions.
>
> -- https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html#modern-security-by-default
In order to follow up on this, I've created GH-526.
/cc @seut
> Dependencies: Limit installation to `urllib3<2`

- CHANGES.txt
- src/crate/client/sqlalchemy/dialect.py
- src/crate/client/sqlalchemy/tests/dialect_test.py
Both methods `CrateDialect.{has_schema,has_table}` need to accept and forward keyword arguments, in order to comply to the intended interface, starting with SQLAlchemy 2.0.
Otherwise, those exceptions would be raised:
```python
TypeError: CrateDialect.has_schema() got an unexpected keyword argument 'info_cache'
TypeError: CrateDialect.has_table() got an unexpected keyword argument 'info_cache'
```
The flaw has been discovered when using SQLAlchemy 2.x to evaluate this snippet, using pandas.
```python
import pandas as pd
import sqlalchemy as sa
engine = sa.create_engine("crate://localhost:4200")
df = pd.DataFrame.from_records([{"foo": "baz", "bar": "qux"}])
df.to_sql(name="testdrive", con=engine, if_exists="replace", index=False)
```
> SA20: Fix `unexpected keyword argument 'info_cache'` on introspection

- CHANGES.txt
- src/crate/client/sqlalchemy/dialect.py
- src/crate/client/sqlalchemy/tests/compiler_test.py
Enable `supports_multivalues_insert` on the CrateDB dialect, mitigating the error reported at GH-534:
CompileError: The 'crate' dialect with current database version
settings does not support in-place multirow inserts
> The Insert construct also supports being passed a list of dictionaries
> or full-table-tuples, which on the server will render the less common
> SQL syntax of "multiple values" - this syntax is supported on backends
> such as SQLite, PostgreSQL, MySQL, but not necessarily others.
> It is essential to note that passing multiple values is NOT the same
> as using traditional `executemany()` form. The above syntax is a special
> syntax not typically used. To emit an INSERT statement against
> multiple rows, the normal method is to pass a multiple values list to
> the …
> SQLAlchemy: Support `INSERT...VALUES` with multiple value sets

- docs/index.rst
As suggested by @hlcianfagna, 84f29fc0f6 brings in more specific queries on the `sys.summits` table, in order to produce more pleasant output. Thanks! Other than this, the patch also removes idiomatic Python-REPL prompts with 30b06e563.
```python
[['AT', 'Großglockner', [12.69444, 47.07417], 3798],
['AT', 'Wildspitze', [10.86722, 46.88528], 3770],
['AT', 'Großvenediger', [12.34639, 47.10917], 3666],
['AT', 'Großes Wiesbachhorn', [12.75528, 47.15639], 3564],
['AT', 'Großer Ramolkogel', [10.95889, 46.84667], 3550],
['AT', 'Schalfkogel', [10.95917, 46.80167], 3540],
['AT', 'Hochvernagtspitze', [10.79611, 46.88139], 3535],
[...]
```
```python
[{'country': 'AT', 'mountain': 'Großglockner', 'coordinates': [12.69444, 47.07417], 'height': 3798},
{'country': 'AT', 'mountain': 'Wildspitze', …
```
> Documentation: Use more specific queries for landing page examples, and remove idiomatic REPL prompt

- CHANGES.txt
- src/crate/client/sqlalchemy/dialect.py
- src/crate/client/sqlalchemy/tests/bulk_test.py
- src/crate/client/sqlalchemy/tests/compiler_test.py
SQLAlchemy's `insertmanyvalues` feature lets you control the batch size of `INSERT` operations using the `insertmanyvalues_page_size` option, which is applicable to all of the engine-, connection-, and statement- objects.
-- https://docs.sqlalchemy.org/core/connections.html#controlling-the-batch-size
The patch will resolve this issue.
- GH-537
/cc @SStorm, @WalBeh, @seut, @hlcianfagna
> SQLAlchemy: Enable the `insertmanyvalues` feature for batch size control

- CHANGES.txt
- src/crate/client/__init__.py
Release the latest updates for improving insert performance/efficiency with pandas, Dask, and friends.
- GH-538
- GH-539
This resolves two issues reported the other day.
- GH-534
- GH-537
/cc @hammerhead, @proddata, @hlcianfagna, @marijaselakovic, @fafahimi
> Release 0.31.0

- CHANGES.txt
- docs/by-example/sqlalchemy/advanced-querying.rst
- src/crate/client/sqlalchemy/dialect.py
Added the two new returning flags to the crate dialect which were introduced with SQLAlchemy 2.0.
Without these the returning clause will not work.
> Enable ``RETURNING`` clause for sqlalchemy 2.0

- CHANGES.txt
- docs/sqlalchemy.rst
- src/crate/client/sqlalchemy/compiler.py
- src/crate/client/sqlalchemy/tests/create_table_test.py
This allows to disable column store for a text column using:
```python
my_data: str = Column(String, crate_index=False, crate_columnstore=False)
```
Which will yield:
```sql
"my_data" TEXT INDEX OFF STORAGE WITH ( columnstore = false )
```
> SQLAlchemy/DDL: Allow to turn off column store

- CHANGES.txt
- docs/sqlalchemy.rst
- src/crate/client/sqlalchemy/compiler.py
- src/crate/client/sqlalchemy/tests/create_table_test.py
CrateDB's SQLAlchemy dialect now handles the `server_default` when generating table DDL.
Fix #454.
> SQLAlchemy/DDL: Handle `server_default` column schema argument well

- CHANGES.txt
- docs/by-example/client.rst
- docs/data-types.rst
- src/crate/client/http.py
- src/crate/client/test_http.py
- src/crate/client/tests.py
As reported at GH-361, when inserting timezone-aware datetime values, the `CrateJsonEncoder` fails with
```python
TypeError: can't subtract offset-naive and offset-aware datetimes
```
This patch intends to fix it.
- https://github.com/daq-tools/kotori/pull/148#discussion_r1237793643
> Allow handling timezone-aware datetime values when inserting or updating

- CHANGES.txt
- src/crate/client/sqlalchemy/tests/__init__.py
- src/crate/client/sqlalchemy/tests/query_caching.py
- src/crate/client/sqlalchemy/types.py
- src/crate/client/tests.py
The SQLAlchemy implementation of CrateDB's `OBJECT` type offers indexed access to the instance's content in form of a dictionary. Thus, it must not use `cache_ok = True` on its implementation, i.e. to signal this part of the compiled SQL clause must not be cached.
Currently, when using those statements subsequently, based on a corresponding ORM schema definition, the second one will yield the wrong results, because it will use the compiled SQL statement of the first one, as it has been cached wrongly. This flaw has been reported by @faymarie, thank you very much.
```python
class Character(Base):
__tablename__ = 'characters'
name = sa.Column(sa.String, primary_key=True)
age = sa.Column(sa.Integer)
data = sa.Column(Object)
```
```python
sa.select(Character).where(Character.data['x'] == 1) …
```
> SQLAlchemy: Fix SQL statement caching for CrateDB's `OBJECT` type

- .github/workflows/tests.yml
- CHANGES.txt
- src/crate/client/sqlalchemy/compiler.py
- src/crate/client/sqlalchemy/dialect.py
- src/crate/client/sqlalchemy/tests/compiler_test.py
- src/crate/client/sqlalchemy/tests/dict_test.py
- src/crate/client/sqlalchemy/tests/match_test.py
- src/crate/client/sqlalchemy/tests/query_caching.py
- src/crate/client/sqlalchemy/tests/warnings_test.py
- src/crate/client/sqlalchemy/types.py
Following up on GH-560, by using the generalized parts of SQLAlchemy's infrastructure for implementing JSON types for a few databases, the CrateDB dialect will be able to leverage the same interfaces, like data casters, thus improving compatibility.
```python
sa.select(Entity).where(Entity.field['attribute'].as_integer() == 42)
```
SQLAlchemy's `sqltypes.JSON` provides a facade for vendor-specific JSON types. Since it supports JSON SQL operations, it only works on backends that have an actual JSON type, which are currently PostgreSQL, MySQL, SQLite, and Microsoft SQL Server.
This patch starts leveraging the same infrastructure, thus bringing corresponding interfaces to the CrateDB dialect. The major difference is that it will not actually do any JSON marshalling, but propagate …
> SQLAlchemy: Use JSON type adapter for implementing CrateDB's `OBJECT`

- .readthedocs.yml
- CHANGES.txt
- docs/by-example/index.rst
- docs/by-example/sqlalchemy/dataframe.rst
- docs/conf.py
- setup.py
- src/crate/client/sqlalchemy/support.py
- src/crate/client/sqlalchemy/tests/bulk_test.py
- src/crate/client/tests.py
Hi again,
in the same spirit as https://github.com/crate/crate-pdo/pull/143, this patch unlocks [CrateDB bulk operations] for efficient batch inserts using [pandas](https://pandas.pydata.org/) and [Dask](https://www.dask.org/). It will accompany a followup to the [Data Processing and Analytics with Dask and CrateDB: A Step-by-Step Tutorial].
The corresponding documentation section can be inspected at [Preview: SQLAlchemy: DataFrame operations](https://crate-python--553.org.readthedocs.build/en/553/by-example/sqlalchemy/dataframe.html).
Andreas.
[CrateDB bulk operations]: https://crate.io/docs/crate/reference/en/latest/interfaces/http.html#bulk-operations
[Data Processing and Analytics with Dask and CrateDB: A Step-by-Step Tutorial]: …
> Add fast-path INSERT method `insert_bulk` for SQLAlchemy/pandas/Dask

- CHANGES.txt
- docs/by-example/sqlalchemy/working-with-types.rst
- docs/sqlalchemy.rst
- src/crate/client/sqlalchemy/dialect.py
- src/crate/client/sqlalchemy/tests/create_table_test.py
- src/crate/client/sqlalchemy/tests/dialect_test.py
- src/crate/client/sqlalchemy/tests/query_caching.py
- src/crate/client/sqlalchemy/tests/update_test.py
The new symbol to represent CrateDB's `OBJECT` column types is now called `ObjectType`. Before, it was just called `Object`, or sometimes `Craty`, which is both either a bit ambiguous, or a bit too fancy.
> SQLAlchemy: Rename leftover occurrences of `Object` to `ObjectType`

- CHANGES.txt
- src/crate/client/sqlalchemy/compiler.py
- src/crate/client/sqlalchemy/dialect.py
- src/crate/client/sqlalchemy/tests/__init__.py
- src/crate/client/sqlalchemy/tests/compiler_test.py
- src/crate/client/test_util.py
At GH-562, @hlcianfagna suggested to use CrateDB's native `ILIKE` operator instead of using SA's generic implementation `lower() LIKE lower()`.
This patch brings in the corresponding visitor methods from the `PGDialect` to the `CrateDialect` implementation.
> SQLAlchemy DQL: Use CrateDB's native `ILIKE` operator

- CHANGES.txt
- src/crate/client/__init__.py
In order to release a cosmetic fix, and an improvement to the SQLAlchemy dialect, to support CrateDB's `ILIKE` operator.
- GH-564
- GH-565
> Release 0.33.0

- .gitignore
- CHANGES.txt
- src/crate/client/http.py
- src/crate/client/test_http.py
When transport-encoding SQL parameters to JSON, Python's UUID type has not been taken into consideration. This patch intends to improve the situation.
> Added automatic conversion of UUIDs to strings.

- CHANGES.txt
- docs/build.json
- docs/by-example/sqlalchemy/advanced-querying.rst
- docs/conf.py
- docs/sqlalchemy.rst
- src/crate/testing/layer.py
- Add missing credits to change log
- Update to crate-docs 2.1.1
- Improve wording
- Update intersphinx reference to SQLAlchemy 2.x
The admonition was:
> E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`.
Apparently, it has been added to flake8 6.1.0, released on July 29, 2023.
> Maintenance: This and that

- CHANGES.txt
- docs/by-example/sqlalchemy/getting-started.rst
- src/crate/client/http.py
- src/crate/client/sqlalchemy/tests/connection_test.py
While investigating GH-569/GH-570, we discovered that both the `timeout` and `pool_size` configuration settings failed being processed well, when obtaining them as URL parameters from the database connection string.
This patch fixes that, and adds corresponding software tests and documentation.
> SQLAlchemy: Fix handling URL parameters `timeout` and `pool_size`

- src/crate/client/sqlalchemy/tests/__init__.py
- src/crate/client/tests.py
- src/crate/testing/tests.py
`unittest.makeSuite` is scheduled to be deprecated with Python 3.13, but already raises quite a number of warnings, obstructing the test suite output. This patch resolves that already.
> Chore: Mitigate deprecation warnings about `unittest.makeSuite`

- docs/by-example/index.rst
- docs/index.rst
There is no easy way to discover the ["By Example" section](https://crate.io/docs/python/en/latest/by-example/) of the documentation from the primary navigation.
This patch intends to add a corresponding item. While at it, it also adds a link to the "Data types" page.
Other than this, the patch improves the text layout/flow a bit, on two other spots.
https://crate-python--574.org.readthedocs.build/en/574/
> Documentation: Add link to "by-example" section to primary navigation

- CHANGES.txt
- src/crate/client/sqlalchemy/compiler.py
- src/crate/client/sqlalchemy/tests/__init__.py
- src/crate/client/sqlalchemy/tests/compiler_test.py
Adjust SQLAlchemy's DDL compiler to ignore foreign key and uniqueness constraints, because CrateDB doesn't support them.
At recent work about unlocking MLflow and LangChain to work together with CrateDB [^1][^2], we needed to add some patches/workarounds.
Both of those to be integrated here are pretty straight-forward and non-invasive, and just mask corresponding SQL features not supported by CrateDB anyway, in order run applications with typical data schemas. Other dialects essentially to the same on their corresponding weak spots.
P.S.: I am intending to bring in this patch before running another release, where users are currently waiting for.
/cc @hlcianfagna, @hammerhead, @surister
[^1]: https://github.com/crate-workbench/mlflow-cratedb
[^2]: …
> SQLAlchemy: Improve DDL compiler to ignore unsupported features

- CHANGES.txt
- src/crate/client/http.py
- src/crate/client/test_http.py
When receiving `DuplicateKeyException` errors from CrateDB, SQLAlchemy should raise corresponding `IntegrityError` exceptions instead of `ProgrammingError`, because applications expect it this way.
This patch evaluates the area preliminarily, mainly whether it will work by using CrateDB's own variants of the canonical DBAPI exceptions, and whether SQLAlchemy will honor that properly.
- GH-578
> Improve exception handling: Properly raise `IntegrityError` exceptions

- docs/sqlalchemy.rst
CrateDB 4.5.0 added the `gen_random_text_uuid()` scalar function, which can also be used within an SQL DDL statement, in order to automatically assign random identifiers to newly inserted records on the server side. In this spirit, it is suitable to be used as a ``PRIMARY KEY`` constraint for SQLAlchemy.
This patch adds a corresponding documentation section how to use it with SQLAlchemy.
- Resolves GH-533
- Replaces GH-580
/cc @surister
> Documentation: Add section about using `gen_random_text_uuid` as auto-PK

- CHANGES.txt
- src/crate/client/sqlalchemy/compiler.py
- src/crate/client/sqlalchemy/tests/compiler_test.py
Pretty straightforward, now queries like `select(table).with_for_update()` will not generate a `FOR UPDATE` statement.
Resolves #577.
> SQLAlchemy: Ignore SQL's "FOR UPDATE" clause

- docs/data-types.rst
Nightly docs build tripped [^1], because Python changed an anchor reference on their documentation. This patch fixes the broken link.
[^1]: https://github.com/crate/crate-python/actions/runs/6415749066/job/17418188033#step:4:466
> Documentation: Fix broken link to Python documentation

- .github/workflows/docs.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- setup.py
After https://github.com/jazzband/geojson/pull/222 has been released with geojson 3.1.0, verify that the package works well on Python 3.12, and announce it within the package's metadata. Also use it right away on other auxiliary CI tasks.
> Add support for Python 3.12

- .github/workflows/tests.yml
On CI, use a more recent CrateDB version for the regular runs.
Download location is https://cdn.crate.io/downloads/releases/crate-5.4.4.tar.gz. Correct or outdated/legacy? /cc @seut
> CI: Use CrateDB 5.4.5

- docs/index.rst
- examples/README.rst
As advised at GH-552, this patch just adds corresponding pointers to the executable code examples at the [`cratedb-examples` repository](https://github.com/crate/cratedb-examples).
This patch will have to go in first.
- https://github.com/crate/cratedb-examples/pull/64
> Documentation: Add pointers to executable code examples

- buildout.cfg
> Would be great if we could switch to using os/arch related download url's [^1] in future.
>
> -- https://github.com/crate/crate-python/pull/593#issuecomment-1794710816
[^1]: https://cdn.crate.io/downloads/releases/cratedb/x64_linux/
- https://github.com/crate/crash/pull/406
> Sandbox: Download Linux variant of CrateDB from os/arch-specific URL

- devtools/setup_ci.sh
Apparently, GH-594 had a flaw when selecting CrateDB nightly, as we can see [on the nightly jobs](https://github.com/crate/crate-python/actions/workflows/nightly.yml), which probably started failing since this change.
This patch adjusts the `sed` command correspondingly, so the nightly job will pick up the CrateDB nightly tarball for Linux again.
> CI: Fix running nightly jobs with CrateDB nightly

- CHANGES.txt
- docs/by-example/client.rst
- docs/by-example/http.rst
- setup.py
- src/crate/client/http.py
- src/crate/client/test_connection.py
Permit `urllib3.Timeout` instances for defining timeout values. Using that, you can configure both the socket `connect` and `read` timeout settings, in seconds.
When defining the `timeout` value as `urllib3.Timeout` instance,
```python
HttpClient(crate_host, timeout=urllib3.Timeout(connect=0.01, read=None))
```
this error is raised:
```python
float() argument must be a string or a real number, not 'Timeout'
```
- Needed by: https://github.com/crate/crash/pull/421
> Permit `urllib3.Timeout` instances for defining timeout values

- src/crate/client/_pep440.py
This patch re-adds the `crate.client._pep440.Version` symbol, now from `verlib2.Version`, so that `crash` does not break.
`crash` broke after releasing `crate==0.35.0`, so I've yanked it again.
```python
ModuleNotFoundError: No module named 'crate.client._pep440'
```
-- https://github.com/crate/crash/actions/runs/7562783871/job/20593938496?pr=421#step:5:29
- https://github.com/crate/crash/pull/422
> Compatibility: Re-add `crate.client._pep440.Version` from `verlib2`

- setup.py
Update test dependency to `pandas<2.2`.
- https://github.com/crate/crash/pull/422
> Tests: Update to pandas 2.1

- .github/workflows/codeql.yml
That patch tripped CodeQL on CI.
- GH-608
Most probably this recent change by GitHub?
- https://github.blog/changelog/2024-01-23-codeql-2-16-python-dependency-installation-disabled-new-queries-and-bug-fixes/
- https://github.com/crate-workbench/sqlalchemy-cratedb/pull/32
> CI: Fix CodeQL by installing Python

- .github/workflows/tests.yml
After updating the ["secrets" on the GitHub project](https://github.com/crate/crate-python/settings/secrets/), this patch is the right solution, superseding GH-610.
- https://github.com/panodata/aika/pull/55
- https://github.com/crate-workbench/mlflow-cratedb/pull/103
> CI: Update to GHA's codecov-action@v4

- setup.py
```python
ImportError: Dask dataframe requirements are not installed.
Please either conda or pip install as follows:
conda install dask                     # either conda install
python -m pip install "dask[dataframe]" --upgrade  # or python -m pip install
```
-- https://github.com/crate/crate-python/actions/runs/8384462414/job/22961820586#step:4:702
- https://github.com/daq-tools/influxio/pull/85
- https://github.com/crate-workbench/cratedb-toolkit/pull/128
- https://github.com/microsoft/LightGBM/issues/6365
- https://github.com/microsoft/LightGBM/pull/6357
> Dependencies: Use `dask[dataframe]` for testing

- requirements.txt
Nightly test runs started failing 3 weeks ago, more specifically on Wed, 22 May 2024 2 o'clock AM GMT.
- https://github.com/crate/crate-python/actions/workflows/nightly.yml
Test runs on Python 3.12 are tripped by this error, coming from zc.buildout.
```python
Traceback (most recent call last):
File "/path/to/.venv/bin/buildout", line 5, in <module>
from zc.buildout.buildout import main
File "/path/to/.venv/lib/python3.12/site-packages/zc/buildout/buildout.py", line 18, in <module>
import zc.buildout.easy_install
File "/path/to/.venv/lib/python3.12/site-packages/zc/buildout/easy_install.py", line 28, in <module>
from pkg_resources import packaging
ImportError: cannot import name 'packaging' from 'pkg_resources'
```
- https://github.com/crate/crate-python/actions/runs/9184331584/job/25256465 …
> Chore: Fix software tests

- setup.cfg
The wheel file name of `crate` still indicates the package would be compatible with Python 2 [^1], which isn't the case. Other packages are doing it right [^2].
[^1]: https://pypi.org/project/crate/0.35.2/#files
[^2]: https://pypi.org/project/cratedb-toolkit/#files
> Chore: Stop building universal wheels, being in Python 3 lands only

- README.rst
A little documentation patch to prepare GH-616.
- https://github.com/crate/crate-python/issues/620
> README: Refer to new SQLAlchemy dialect `sqlalchemy-cratedb`

- .github/workflows/tests.yml
What the title says.
Unfortunately, we currently can't use "latest" or "nightly" here, because of the venerable x64_mac build matrix anomaly of CrateDB.
- GH-624
> CI: Update from CrateDB 5.4.5 to 5.7.2

- CHANGES.txt
- src/crate/client/__init__.py
Relating to the [section about thread safety in PEP 0249](https://peps.python.org/pep-0249/#threadsafety) ...
- The driver currently configures `threadsafety = 2`, which means "Threads may share the module and connections."
- Now, it will configure `threadsafety = 1`, which means "Threads may share the module, but not connections."
@hlcianfagna asked:
> When using the python driver, is it ok to share a connection with multiple threads each opening their own cursor or should each thread have its own connection?
@amotl said:
> Thread-per-connection sounds reasonable.
@mfussenegger said:
> I think it currently relies on Python GIL, and afaik if you'd share a connection with the `multiprocessing` module across processes, things would break. So, it could be worth changing that to 1. …
> Configure DB API interface attribute `threadsafety = 1`: Threads may share the module, but not connections

- README.rst
- docs/index.rst
Mention the switchover to `sqlalchemy-cratedb` both on the project's README, and the index page of the documentation, in order to give users who might be running into relevant flaws a better chance to discover the solution.
- [README » Migration Notes](https://github.com/crate/crate-python/blob/amo/improve-sa-migration-docs/README.rst#migration-notes)
- [Documentation » Migration Notes](https://crate-python--636.org.readthedocs.build/en/636/#migration-notes)
- GH-616
- GH-621
/cc @seut, @matriv
> Documentation: Improve guidance about migrating to `sqlalchemy-cratedb`

- CHANGES.txt
- src/crate/client/exceptions.py
- src/crate/client/test_exceptions.py
If the `error_trace` payload is available, add it to the string representation of the Error class.
This way, any layer using the driver, e.g. our SqlAlchemy Dialect, can display the error trace without to handle concrete exceptions. Additionally, handling the concrete exception and reading the `self.error_trace` variable won't be always possible (e.g. in generic SqlAlchemy abstractions).
If the error_trace is available is already depending on the concrete `connect(error_trace=True)` attribute and thus in control of the user.
> Add `error_trace` to string representation of an Error

- requirements.txt
Roll back a temporary version pinning on the `setuptools` package.
- https://github.com/crate/crate-python/pull/617
- GH-645
- https://github.com/crate/crate-python/security/dependabot/1
> Sandbox: Don't limit setuptools version

- .github/workflows/tests.yml
- bootstrap.sh
Maintenance: Just update CrateDB to use the most recent version.
Unfortunately, the test suite currently can't use neither of "latest", nor "testing".
- GH-624
> Chore: Use CrateDB 5.8.3 for testing

- .github/workflows/codeql.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- DEVELOP.rst
- bootstrap.sh
[uv](https://docs.astral.sh/uv/) has a [pip interface](https://docs.astral.sh/uv/#the-pip-interface), that works pretty well emulating all sorts of `pip` incantations already.
Aliasing vanilla `pip` has been verified on my workstation, and it also works pretty well, so we can offer it as an optional sandbox feature without needing to populate all invocation spots where `pip` is used.
> Sandbox: Optionally use `uv` package manager to save cycles

- .github/workflows/tests.yml
There are no nightly builds for macOS, so the test matrix has an anomaly. C'est la vie.
By restructuring this spot on the CI configuration, at least we don't need to bump versions manually any longer to prevent falling behind CrateDB development. While this just applies to the Linux slot, it is much better than nothing, and before.
> CI: Use CrateDB `nightly` for PRs on Linux, lock version only on macOS

- .github/workflows/tests.yml
- DEVELOP.rst
- bootstrap.sh
- docs/conf.py
- pyproject.toml
- setup.cfg
- setup.py
- src/crate/__init__.py
- src/crate/client/__init__.py
- src/crate/client/blob.py
- src/crate/client/connection.py
- src/crate/client/converter.py
- src/crate/client/cursor.py
- src/crate/client/exceptions.py
- src/crate/client/http.py
- src/crate/testing/layer.py
- src/crate/testing/util.py
- tests/client/layer.py
- tests/client/settings.py
- tests/client/test_connection.py
- tests/client/test_cursor.py
- tests/client/test_exceptions.py
- tests/client/test_http.py
- tests/client/tests.py
- tests/testing/test_layer.py
- tests/testing/tests.py
- Run the ruff code formatter and linter on the code base, and the mypy type checker.
- Invoke the "lint" job also on CI.
Before releasing 1.0.0, we would like to get the shape of the repository in order. This patch is one in a series to support that.
No other functional changes inside.
- GH-659
> QA and CI: Format code using ruff. Validate using ruff and mypy.

- docs/by-example/http.rst
Dear Sebastian,
this patch is based on the commit 575f6a3c60 you submitted the other day with crate/crate-python#431. I would like to investigate if it might improve timing behaviour/flakyness on CI, as documented at crate/crate-python#404.
Andreas.
> Tests: Use small timeouts for server selection tests in `http.txt`

- CHANGES.txt
- src/crate/client/cursor.py
- tests/client/test_cursor.py
Chore. Carry-over from https://github.com/crate/crate-python/pull/660#discussion_r1825654061.
> Error handling: Use `ValueError` exceptions instead of `assert`

- setup.py
A library mostly shouldn't apply version pinning when not exactly needed. Only applications usually do, and libraries should be able to cope with different up- and downstream-versions.
Considering that both runtime dependencies are stable on their own, this should not cause too many forseeable headaches. When urllib3 v3 will be released, it might be different, but honestly I can't imagine it will be breaking its designated interface too much, if at all.
> Dependencies: Remove version pinning of urllib3 and verlib2

- CHANGES.txt
- docs/by-example/cursor.rst
- docs/query.rst
- src/crate/client/connection.py
- src/crate/client/converter.py
- src/crate/client/cursor.py
- tests/client/test_cursor.py
Python: Remove invocations to deprecated `datetime.utcfromtimestamp()`.
World: Make datetime handling like it's 2024.
This is a possible BREAKING CHANGE about returned Python ``datetime`` objects:
> Removed the use of "naive" Python ``datetime`` objects, i.e. instances without ``tzinfo`` attribute set.
When no ``time_zone`` information is specified when creating a database connection or cursor, ``datetime`` objects will now use Coordinated Universal Time (UTC), like CrateDB is storing timestamp values in this format.
This update is coming from a deprecation of Python's ``datetime.utcfromtimestamp()``, which is effectively also phasing out the use of "naive" timestamp objects in Python, in favor of using timezone-aware objects, also to represent datetimes in UTC. It may be a breaking …
> Timestamp values: Remove the use of "naive" Python `datetime` objects

- .github/workflows/nightly.yml
Aftermath fixes to recent project/repository updates.
- GH-660
> CI: Fix "nightly" job: flake8 has been replaced with ruff. Also, add Python 3.13.

- .github/workflows/codeql.yml
- .github/workflows/docs.yml
- .github/workflows/tests.yml
- DEVELOP.rst
- README.rst
- devtools/create_tag.sh
- docs/index.rst
- tests/assets/pki/readme.rst
Last touch to improve repository details before releasing 1.0.0.
> Maintenance: Rename default branch to `main`

- .github/workflows/codeql.yml
- .github/workflows/release.yml
A few aftermath fixes that have been revealed by running the release procedure.
> CI: Fix CodeQL and Release jobs

- .github/workflows/codeql.yml
Without `id: analyze` the `steps.analyze.output` values will be undefined:
https://github.com/crate/crate-python/blob/31f53c026455902e76d1bae96d172e7cb21d67be/.github/workflows/codeql.yml#L79-L80
> Add missing `id:` field

- CHANGES.rst
... by omitting `__init__.py` from `crate` namespace package altogether, see "PEP 420" [1] and "Package Discovery and Namespace Package » Finding namespace packages" [2].
[1] https://peps.python.org/pep-0420/
[2] https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#namespace-packages
- https://github.com/crate/crate-python/pull/666
- https://github.com/crate/crash/pull/453
- https://github.com/crate/crate-qa/pull/327
> Python: Fix "implicit namespace packages" migration

- .github/workflows/codeql.yml
- src/crate/client/__init__.py
GitHub's CodeQL flags [1] a few spots unqualified with "Unused global variable" [2].
Based on a suggestion [3], this patch attempts to use the `advanced-security/dismiss-alerts` [4] GitHub Action recipe to provide measures to suppress CodeQL flagging by using inline code annotations.
[1] https://github.com/crate/crate-python/security/code-scanning
[2] https://codeql.github.com/codeql-query-help/python/py-unused-global-variable/
[3] https://github.com/github/codeql/issues/11427#issuecomment-1721059096
[4] https://github.com/advanced-security/dismiss-alerts
- https://github.com/advanced-security/dismiss-alerts/issues/118
> Chore: Suppress unqualified CodeQL admonitions

- .github/workflows/nightly.yml
> CI: Provide Python 3.7. EOL, it was removed from recent GHA runners

- docs/by-example/http.rst
> Chore: Fix test case because https://example.org/ responds differently

- src/crate/client/http.py
- tests/client/test_http.py
Separately from https://github.com/crate/sqlalchemy-cratedb/pull/195, let's explore which changes are needed when disabling orjson's `OPT_PASSTHROUGH_DATETIME` option.
> Marshalling: Disable option `orjson.OPT_PASSTHROUGH_DATETIME`

- CHANGES.rst
- setup.py
- src/crate/client/http.py
- tests/client/test_http.py
Using [orjson](https://pypi.org/project/orjson/) for JSON marshalling can yield performance wins. It has been used in CrateDB Toolkit already, in that case its sister library [orjsonl](https://pypi.org/project/orjsonl/). Thanks, @widmogrod.
- GH-689
- https://github.com/crate/cratedb-toolkit/pull/270
- https://github.com/crate/crash/pull/459
- https://github.com/crate/cratedb-toolkit/pull/349
- https://github.com/crate/cratedb-examples/pull/811
- https://github.com/crate/sqlalchemy-cratedb/pull/195
- https://github.com/crate/langchain-cratedb/pull/23
- https://github.com/crate/academy-fundamentals-course/pull/49
- https://github.com/crate/cloud-api/pull/3038
- https://github.com/crate/stevedore/pull/325
- https://github.com/crate/grand-central/pull/189
> Use `orjson` to improve JSON marshalling performance

- .github/workflows/codeql.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
What the title says. This [error on CI](https://github.com/crate/crate-python/actions/runs/13373454490/job/37431942284?pr=698) indicated something was wrong. The setup here was one of our first times using uv on GHA, so it was clear it needed to be improved as we go.
> CI: Improve setup of and caching with uv

- requirements.txt
```python
ModuleNotFoundError: No module named 'setuptools.package_index'
```
-- https://github.com/crate/crate-python/actions/runs/14850452065/job/41692926889#step:5:97
```python
SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Missing Authority Key Identifier
```
- https://github.com/crate/crate-python/issues/708
> Chore: Fix build wrt. `setuptools` and `urllib3`

- .github/workflows/codeql.yml
> CI: Use Python 3.13 for CodeQL analysis

- .github/workflows/tests.yml
As you may know, both 3.7 and 3.8 are EOL, they receive no support/security fixes, nothing.
For that reason I would propose to remove them from the test matrix, we are also seeing new dependencies updates fail on 3.7, because of the libraries using >3.7 syntax (walrus operator), an example of this is https://github.com/crate/crate-python/actions/runs/15392143903/job/43303839083
We previously had a discussion on whether or not to keep 3.8 at https://github.com/crate/cratedb-sqlparse/pull/173
- Title
> Remove python 3.7 and 3.8 from test matrix.

- src/crate/testing/layer.py
Increased the wait time threshold from 30 to 60 seconds before raising an error.
> Increase wait time threshold for Crate instance startup
