crate/crate-python

CHANGES.txt, src/crate/client/sqlalchemy/tests/dict_test.py, src/crate/client/sqlalchemy/types.py
setting properties with type ObjectArray to None resulted in setting an array with None -> [None]
This fixes this issue.
=> allow object arrays to be set to none

README.rst
because pypip.in images where broken
=> updated badges in readme to use shields.io

src/crate/client/http.txt, src/crate/testing/layer.py, src/crate/testing/layer.txt, src/crate/testing/tests.py
should fix https://travis-ci.org/crate/crash/jobs/85694200
=> crate test layer: wait for master to be elected

README.rst
pip is the recommended way to install packages
=> remove easy_install install instructions

src/crate/client/sqlalchemy/dialect.txt, versions.cfg
=> updated crate and sqlalchemy versions

src/crate/testing/test_layer.py, versions.cfg
* updated Crate to 0.55.2 (stable)
=> added missing test for parsing http url

src/crate/client/test_http.py
regression test for #179 / #180 
@mfussenegger wanna take a look?
=> added regression test for adding non-https servers on redirect

.travis.yml, docs/sqlalchemy.txt, src/crate/client/http.py, src/crate/client/http.txt, src/crate/client/sqlalchemy/reflection.txt, src/crate/client/test_http.py, versions.cfg
=> testing: updated CrateDB version to 1.0.0

src/crate/testing/layer.py
of testing layer to lowercase strings 'true'/'false'.
=> Convert boolean True/False values for additional settings

docs/sqlalchemy.txt
=> document type mapping

CHANGES.txt, src/crate/client/sqlalchemy/compiler.py, src/crate/client/sqlalchemy/tests/create_table_test.py
Fixes: https://github.com/crate/crate-python/issues/252
=> Added missing "translation" of NUMERIC and DECIMAL data types.

src/crate/client/http.py, src/crate/client/http.txt
sometimes the test query took less than 100ms
=> testing: reduced timeout in client test

docs/client.txt
Follow up to b8a12bc959ae88b38838eefdef6ebe1048fd01b1
=> Fix test failures

src/crate/client/sqlalchemy/types.py
https://lgtm.com/projects/g/crate/crate-python/alerts/?mode=list
=> Fix LGTM alerts

docs/connect.txt
I just added a new set of styles for admonitions in the docs. I am now going through each docs project and improving our use of admonitions
=> improve use of admonitions

CHANGES.txt, src/crate/testing/layer.py
=> Clean up PoolManager resources on CrateLayer stop

.travis.yml, CHANGES.txt, docs/appendices/compatibility.txt, docs/getting-started.txt, setup.py, tox.ini
Added explicit support of Python 3.7 and made that the recommended version.
=> Add explicit Python 3.7 support

docs/appendices/compatibility.txt, docs/appendices/data-types.txt, docs/blobs.txt, docs/connect.txt, docs/getting-started.txt, docs/query.txt, docs/sqlalchemy.txt
Changes headers from title case to sentence case.
=> Changes headers from title case to sentence case

docs/appendices/compatibility.txt, docs/appendices/data-types.txt, docs/appendices/index.txt, docs/blobs.txt, docs/connect.txt, docs/getting-started.txt, docs/index.txt, docs/query.txt, docs/sqlalchemy.txt
Change directive headings and page titles to sentence case
=> Change directive headings and page titles to sentence case

docs/index.txt
Changes the header on the index page to title case.
=> Change index header to title case

CHANGES.txt, src/crate/client/__init__.py
=> Prepare release 0.23.2

.github/workflows/main.yml
So that tests run on PRs from forks
=> Run github actions on PRs and on push to master

CHANGES.txt, docs/connect.txt, src/crate/client/connection.py, src/crate/client/http.py
Squashed version of https://github.com/crate/crate-python/pull/342 with
some style fixes.
Cannot push to the fork, so created a new PR.
=> Add backoff_factor in connection to configure retry interval

CHANGES.txt
In relation to issue https://github.com/crate/crate-python/issues/348
For the next release description
=> driver attribute addition

CHANGES.txt, src/crate/client/__init__.py
=> Prepare 0.24.0 release

CHANGES.txt, setup.py, src/crate/client/__init__.py
=> Prepare release 0.25.0

.github/workflows/main.yml, src/crate/client/doctests/sqlalchemy.txt, src/crate/testing/doctests/layer.txt
Merge after the next CrateDB nightly build is built. See https://github.com/crate/crate/pull/10343
=> Run tests against crate nightly in github actions.

.github/workflows/main.yml, versions.cfg
On hold. Merge once 4.2.3 hotfix release is out. See https://github.com/crate/crate/pull/10343
=> Update CrateDB in testing layer to 4.2.3.

src/crate/client/sqlalchemy/tests/dialect_test.py
Hi there,
7739d442 is a maintenance patch coming from #391's 76129db5.
Andreas.
=> Tests: Improve fake cursor handling

.github/workflows/tests.yml, CHANGES.txt, setup.py, versions.cfg
=> CrateDB 4.8.0, SQLAlchemy 1.3.24, Python 3.10

CHANGES.txt, src/crate/client/__init__.py
=> Release 0.27.1

CHANGES.txt, src/crate/client/__init__.py
Prepare new release in order to ship improvements from #459.
=> Release 0.27.2

CHANGES.txt, src/crate/client/__init__.py
To get computed columns out to the customer requesting it.
=> Release 0.28

docs/sqlalchemy.rst, setup.py
=> Document `__table args__`

setup.py
The `geojson-3.0.0` package has been released yesterday.
- https://github.com/jazzband/geojson/blob/main/CHANGELOG.rst#300-2022-01-26
- https://pypi.org/project/geojson/3.0.0/
=> Dependencies: Update to geojson 3.0.0

.github/workflows/codeql.yml, .github/workflows/docs.yml, .github/workflows/nightly.yml, .github/workflows/tests.yml, bootstrap.sh, devtools/setup_ci.sh
=> CI: Dependency version bumps, and a few cleanups

CHANGES.txt, src/crate/client/__init__.py
=> Release 0.30.1

setup.py
Align with classifiers and what's tested by CI.
=> Chore: Adjust minimum Python version in project metadata

CHANGES.txt, src/crate/client/__init__.py
Running a release in order to ship the improvement GH-546 by @Taliik. Thanks again.
=> Release 0.31.1

CHANGES.txt, src/crate/client/__init__.py
=> Release 0.32.0

CHANGES.rst, src/crate/client/__init__.py
=> Release 1.0.0

.github/workflows/codeql.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/tests.yml
=> CI: Migrate to `astral-sh/setup-uv`

docs/build.json
=> Update build.json to 2.1.2
